# Purge any INSTALLED archive from the code path so the source tree wins
# while developing. Both names matter: our modules are still namespaced
# `Phx.New.*` (deliberately — it keeps the upstream rebase clean), so a
# stock phx_new archive would clash with them just as an older cms_new would.
for path <- :code.get_path(),
    Regex.match?(~r/(cms_new|phx_new)-[\w\.\-]+\/ebin$/, List.to_string(path)) do
  Code.delete_path(path)
end

defmodule Phx.New.MixProject do
  use Mix.Project

  @version "1.8.8"
  @scm_url "https://github.com/Code-My-Spec/cms_new"

  # If the elixir requirement is updated, we need to update:
  #
  #   1. all mix.exs generated by the installer
  #   2. guides/introduction/installation.md
  #   3. guides/deployment/releases.md
  #   4. test/test_helper.exs at the root
  #   5. installer/lib/mix/tasks/phx.new.ex
  #
  @elixir_requirement "~> 1.20"

  def project do
    [
      app: :cms_new,
      start_permanent: Mix.env() == :prod,
      version: @version,
      elixir: @elixir_requirement,
      deps: deps(),
      aliases: aliases(),
      package: [
        maintainers: [
          "Chris McCord",
          "José Valim",
          "Gary Rennie",
          "Jason Stiebs"
        ],
        licenses: ["MIT"],
        links: %{"GitHub" => @scm_url},
        files: ~w(lib templates mix.exs README.md)
      ],
      source_url: @scm_url,
      docs: docs(),
      homepage_url: "https://codemyspec.com",
      description: """
      CodeMySpec project generator.

      Provides a `mix cms.new` task to bootstrap a new Phoenix application
      that already satisfies every CodeMySpec harness convention — no
      model-driven setup pass required.
      """
    ]
  end

  def cli do
    [preferred_envs: [docs: :docs]]
  end

  def application do
    [
      extra_applications: [:eex, :crypto, :public_key]
    ]
  end

  def deps do
    [
      {:ex_doc, "~> 0.24", only: :docs}
    ]
  end

  defp docs do
    [
      source_url_pattern: "#{@scm_url}/blob/v#{@version}/installer/%{path}#L%{line}"
    ]
  end

  defp aliases do
    [
      "hex.publish": [
        &copy_agents_md/1,
        "hex.publish"
      ]
    ]
  end

  defp copy_agents_md(_) do
    File.cp_r!(
      Path.expand("../usage-rules", __DIR__),
      Path.expand("./templates/phoenix-usage-rules", __DIR__)
    )
  end
end
